[project]
name = "mecab-ko-dic-admin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = ["baekhum.19 <baekhum.19@gmail.com>"]
requires-python = ">=3.12,<3.13"
dependencies = [
    "django-environ>=0.11.2",
    "django-ninja>=1.3.0",
    "django>=5.2,<5.3",
    "jupyter>=1.1.1",
    "pre-commit>=3.8.0",
    "psycopg[binary]>=3.3.3",
    "pytest>=8.3.2",
    "ruff>=0.6.3",
]
