# Generated by Django 5.1 on 2024-09-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecab_Ko_Dic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('표층형', models.CharField(db_column='surface_form', max_length=100)),
                ('품사_태그', models.CharField(db_column='pos_tag', max_length=100)),
                ('의미_부류', models.CharField(blank=True, db_column='semantic_class', max_length=100, null=True)),
                ('종성_유무', models.CharField(db_column='final_consonant', max_length=1)),
                ('읽기', models.CharField(db_column='reading', max_length=100)),
                ('타입', models.CharField(blank=True, db_column='type', max_length=100, null=True)),
                ('첫번째_품사', models.CharField(blank=True, db_column='first_pos', max_length=100, null=True)),
                ('마지막_품사', models.CharField(blank=True, db_column='last_pos', max_length=100, null=True)),
                ('표현', models.CharField(blank=True, db_column='expression', max_length=255, null=True)),
            ],
        ),
    ]
