# Generated by Django 5.1 on 2026-05-09 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecab_ko_dic', '0003_alter_mecab_ko_dic_품사_태그'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_column='word', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'stopword',
            },
        ),
        migrations.CreateModel(
            name='SynonymGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'synonym_group',
            },
        ),
        migrations.CreateModel(
            name='SynonymWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_column='word', max_length=100)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='words', to='mecab_ko_dic.synonymgroup')),
            ],
            options={
                'db_table': 'synonym_word',
            },
        ),
    ]
