# Generated by Django 5.1 on 2026-05-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecab_ko_dic', '0004_stopword_synonymgroup_synonymword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stopword',
            options={'verbose_name': '불용어', 'verbose_name_plural': '불용어 목록'},
        ),
        migrations.AlterModelOptions(
            name='synonymgroup',
            options={'verbose_name': '동의어 그룹', 'verbose_name_plural': '동의어 그룹 목록'},
        ),
        migrations.AlterModelOptions(
            name='synonymword',
            options={'verbose_name': '동의어 단어', 'verbose_name_plural': '동의어 단어 목록'},
        ),
        migrations.AlterField(
            model_name='stopword',
            name='word',
            field=models.CharField(db_column='word', max_length=100, unique=True, verbose_name='불용어'),
        ),
        migrations.AlterField(
            model_name='synonymgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='synonymgroup',
            name='name',
            field=models.CharField(db_column='name', max_length=100, unique=True, verbose_name='그룹명'),
        ),
        migrations.AlterField(
            model_name='synonymword',
            name='group',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='words', to='mecab_ko_dic.synonymgroup', verbose_name='동의어 그룹'),
        ),
        migrations.AlterField(
            model_name='synonymword',
            name='word',
            field=models.CharField(db_column='word', max_length=100, verbose_name='단어'),
        ),
        migrations.AlterUniqueTogether(
            name='synonymword',
            unique_together={('group', 'word')},
        ),
    ]
