# Generated by Django 5.1 on 2026-05-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecab_ko_dic', '0005_alter_stopword_options_alter_synonymgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecab_ko_dic',
            name='is_active',
            field=models.BooleanField(db_column='is_active', db_index=True, default=True, verbose_name='활성 여부'),
        ),
        migrations.AlterField(
            model_name='mecab_ko_dic',
            name='origin_type',
            field=models.CharField(choices=[('SYSTEM', '시스템'), ('USER', '사용자'), ('COMPOUND', '복합명사')], db_column='origin_type', db_index=True, default='SYSTEM', max_length=10, verbose_name='출처'),
        ),
        migrations.AlterField(
            model_name='mecab_ko_dic',
            name='읽기',
            field=models.CharField(db_column='reading', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mecab_ko_dic',
            name='표층형',
            field=models.CharField(db_column='surface_form', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mecab_ko_dic',
            name='품사_태그',
            field=models.CharField(choices=[('NNG', '일반 명사'), ('NNP', '고유 명사'), ('NNB', '의존 명사'), ('NNBC', '단위를 나타내는 명사'), ('NR', '수사'), ('NP', '대명사'), ('VV', '동사'), ('VA', '형용사'), ('VX', '보조 용언'), ('VCP', '긍정 지정사'), ('VCN', '부정 지정사'), ('MM', '관형사'), ('MAG', '일반 부사'), ('MAJ', '접속 부사'), ('IC', '감탄사'), ('JKS', '주격 조사'), ('JKC', '보격 조사'), ('JKG', '관형격 조사'), ('JKO', '목적격 조사'), ('JKB', '부사격 조사'), ('JKV', '호격 조사'), ('JKQ', '인용격 조사'), ('JX', '보조사'), ('JC', '접속 조사'), ('EP', '선어말 어미'), ('EF', '종결 어미'), ('EC', '연결 어미'), ('ETN', '명사형 전성 어미'), ('ETM', '관형형 전성 어미'), ('XPN', '체언 접두사'), ('XSN', '명사 파생 접미사'), ('XSV', '동사 파생 접미사'), ('XSA', '형용사 파생 접미사'), ('XR', '어근'), ('SF', '마침표, 물음표, 느낌표'), ('SE', '줄임표 …'), ('SSO', '여는 괄호 (, ['), ('SSC', '닫는 괄호 ), ]'), ('SC', '구분자 , · / :'), ('SY', '기호'), ('SL', '외국어'), ('SH', '한자'), ('SN', '숫자')], db_column='pos_tag', db_index=True, max_length=4),
        ),
    ]
