# Generated by Django 5.1 on 2026-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecab_ko_dic', '0006_alter_mecab_ko_dic_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecab_ko_dic',
            name='품사_태그',
            field=models.CharField(db_column='pos_tag', db_index=True, max_length=50),
        ),
    ]
