# Generated by Django 5.1 on 2026-05-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecab_ko_dic', '0008_alter_mecab_ko_dic_의미_부류'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mecab_ko_dic',
            constraint=models.UniqueConstraint(fields=('표층형', '품사_태그'), name='unique_surface_pos'),
        ),
    ]
