# Generated by Django 5.2.17 on 2026-09-02 13:33

import mecab_ko_dic.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mecab_ko_dic", "0010_mecab_ko_dic_mecab_origin_type_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mecab_ko_dic",
            name="품사_태그",
            field=models.CharField(
                db_column="pos_tag", db_index=True, max_length=50, validators=[mecab_ko_dic.models.validate_pos_tag]
            ),
        ),
    ]
