services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - $POSTGRES_DATA_DIR:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    restart: always
